# Read the Docs settings
# RTD version
version: 2

# Output formats for the documentation
formats: all

# Python environment settings
python:
  version: "3.7"
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

# Sphinx settings
sphinx:
  builder: dirhtml
  configuration: docs/source/conf.py
