name: Continuous Integration
on:
  push:
    branches: [development]
  pull_request:
    branches: [main, development]

jobs:
  tests:
    name: Run CI commands
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install continuous integration dependencies
        run: pip install -r requirements/ci.txt
      - name: Run tox
        run: tox
