name: Tests
on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.7, 3.6]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2.3.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install development dependencies
        run: pip install -r requirements/dev.txt
      - name: Run tests with tox
        run: tox
